# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
  - stage: Build
    displayName: Build Package
    jobs:
        - job: build
          displayName: build project 

          steps:
          - task: PowerShell@2
            inputs:
              targetType: filePath
              filePath: '$(Build.SourcesDirectory)\Data\UiPathPack.ps1'
              arguments: 
                -project_path $(Build.SourcesDirectory)\project.json
                -destination_folder '$(Build.SourcesDirectory)\Data' -autoVersion


 
